'use strict';
const $=id=>document.getElementById(id);
const groups=[
  {title:'01 / Identity & purpose',open:true,fields:[
    ['principal','Principal / responsible person','text','Who is proposing this authority?'],
    ['agent_name','Agent name','text','A descriptive name supplied in the brief.'],
    ['purpose','Purpose','textarea','What work should this agent be able to do?',true],
    ['agent_id','Registered agent ID','text','Optional for a document review. Do not invent an ID.',true]]},
  {title:'02 / Spending boundaries',open:true,fields:[
    ['currency','Currency','currency','This authoring package supports EUR only.'],
    ['per_action_limit_cents','Per-action ceiling (€)','money','A hard ceiling for one action.'],
    ['period_limit_cents','Calendar-month cap (€)','money','Total proposed spending in one calendar month.'],
    ['approval_threshold_cents','Human review strictly above (€)','money','Equal to the threshold does not trigger amount review.'],
    ['max_uses','Maximum uses','integer','Blank means unknown, not unlimited.',true]]},
  {title:'03 / Scope & counterparties',open:false,fields:[
    ['allowed_categories','Allowed categories','list','One per line. Blank = unknown; [] = explicitly empty.',true],
    ['blocked_categories','Blocked categories','list','One per line. Blank = unknown; [] = explicitly empty.',true],
    ['approved_counterparties','Approved counterparties','list','Use only supplied names. One per line.',true],
    ['allowed_tools','Allowed tools','list','Design requirement; runtime enforcement is unverified.'],
    ['approved_resources','Approved resources','list','Design requirement; runtime enforcement is unverified.']]},
  {title:'04 / Human ownership',open:true,fields:[
    ['approval_owner','Amount approver','text','Who reviews requests above the amount threshold?',true],
    ['require_new_counterparty_approval','Review new counterparties?','boolean','This is a separate approval route.'],
    ['new_counterparty_approval_owner','New-counterparty approver','text','Never inferred from the amount approver.'],
    ['revocation_owner','Revocation owner','text','Who is responsible for revoking the authority?',true]]},
  {title:'05 / Validity & notes',open:false,fields:[
    ['valid_from','Valid from, with UTC offset','text','For example: 2026-09-15T09:00:00+01:00',true],
    ['expires_at','Expires at, with UTC offset','text','Must be later than the start of validity.',true],
    ['notes','Additional supplied notes','textarea','Context for human review. No runtime instructions.',true]]}
];
const fields=groups.flatMap(g=>g.fields);
const labels=Object.fromEntries(fields.map(([key,label])=>[key,label]));
const notes={procurement:'A fictional research agent with stated limits and separate approval owners. Example dates and identities grant no current authority.',
  'approval-gap':'The new-counterparty approver is deliberately unspecified. The amount approver cannot silently fill that gap.',
  'conflicting-boundaries':'The example allows and blocks the same category, and puts the amount-review threshold above the per-action ceiling.',
  blank:'Your own brief. Every field starts unknown; no fictional identities, limits or dates are carried over.'};
const findingTitles={needs_human_input:'A decision needs an owner or value',missing_provenance:'A source note is missing',identity_not_bound:'The agent identity is not bound',empty_allowlist:'An empty allowlist needs interpretation',category_conflict:'A category is both allowed and blocked',zero_boundary:'A zero limit needs interpretation',cap_above_period:'The action ceiling exceeds the monthly cap',unreachable_amount_review:'The amount-review threshold cannot be reached',invalid_window:'The validity window conflicts',new_counterparty_scope:'The counterparty scope needs review',verify_runtime_coverage:'Verify coverage in the execution path'};
let baseline={schema_version:1,mandate:{},evidence:{}},worker=null,timer=null,busy=false,loadId=0,runId=0,latest=null;
function el(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function buildForm(){for(const group of groups){const details=el('details',undefined,'field-group');details.open=group.open;details.append(el('summary',group.title));const grid=el('div',undefined,'fields');for(const [key,label,type,hint,wide] of group.fields){const box=el('div',undefined,'field'+(wide?' wide':''));const lab=el('label',label);lab.htmlFor='field-'+key;const input=el(['list','textarea'].includes(type)?'textarea':['boolean','currency'].includes(type)?'select':'input');input.id='field-'+key;input.name=key;input.setAttribute('aria-describedby','hint-'+key);if(input.tagName==='INPUT'){input.type='text';input.maxLength=4000;if(['money','integer'].includes(type))input.inputMode=type==='money'?'decimal':'numeric';}if(input.tagName==='TEXTAREA'){input.maxLength=type==='list'?100000:4000;input.rows=type==='list'?3:2;}if(input.tagName==='SELECT'){for(const [value,text] of type==='boolean'?[['','Unknown'],['true','Required'],['false','Not required']]:[['','Unknown'],['EUR','EUR']]){const option=el('option',text);option.value=value;input.append(option);}}const small=el('small',hint);small.id='hint-'+key;box.append(lab,input,small);grid.append(box);}details.append(grid);$('field-groups').append(details);}}
function centsText(value){return Math.trunc(value/100)+'.'+String(value%100).padStart(2,'0');}
function display(v,key){if(v===null||v===undefined)return 'Needs human input';if(Array.isArray(v))return v.length?v.join('; '):'Explicitly empty';if(typeof v==='boolean')return v?'Yes':'No';if(key.endsWith('_cents'))return '€'+centsText(v);return String(v);}
function fieldError(key,message){const error=new Error(message);error.field=key;return error;}
function collect(){const mandate={},evidence={};for(const [key,label,type] of fields){const value=$('field-'+key).value.trim();let parsed=null;if(value){if(type==='money'){if(!/^\d+(?:\.\d{1,2})?$/.test(value))throw fieldError(key,label+': enter a nonnegative amount with at most two decimal places.');const [whole,fraction='']=value.split('.');const cents=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));if(cents>=9007199254740991n)throw fieldError(key,label+': amount is too large.');parsed=Number(cents);}else if(type==='integer'){if(!/^\d+$/.test(value)||!Number.isSafeInteger(Number(value))||Number(value)<=0||Number(value)>=9007199254740991)throw fieldError(key,label+': enter a positive safe whole number.');parsed=Number(value);}else if(type==='list'){parsed=value==='[]'?[]:value.split(/\r?\n/).map(s=>s.trim()).filter(Boolean);}else if(type==='boolean')parsed=value==='true';else parsed=value;}mandate[key]=parsed;if(parsed!==null){if(JSON.stringify(parsed)===JSON.stringify(baseline.mandate[key])&&baseline.evidence[key])evidence[key]=baseline.evidence[key];else evidence[key]='Supplied in browser brief: '+JSON.stringify(parsed);}}return {schema_version:1,mandate,evidence};}
function preview(){try{$('input-preview').textContent=JSON.stringify(collect(),null,2);$('download-input').disabled=busy;}catch(error){$('input-preview').textContent=error.message;$('download-input').disabled=true;}}
function setBadge(text,state){$('status-badge').textContent=text;$('status-badge').dataset.state=state||'';}
function clearReport(message='Brief changed. Prepare the review again.'){latest=null;$('report').hidden=true;$('empty-state').hidden=false;$('status').textContent=message;setBadge('READY');}
function setBusy(value){busy=value;$('brief-form').querySelectorAll('input,select,textarea').forEach(node=>node.disabled=value);$('example').disabled=value;$('run').disabled=value;$('cancel').hidden=!value;$('run').firstChild.textContent=value?'Preparing… ':'Prepare review ';$('download-input').disabled=value;}
function fill(data){baseline=data;for(const [key,,type] of fields){const value=data.mandate[key];$('field-'+key).value=value===null||value===undefined?'':type==='money'?centsText(value):Array.isArray(value)?value.length?value.join('\n'):'[]':String(value);}preview();}
async function loadExample(key){const id=++loadId;clearReport('Loading the brief…');$('run').disabled=true;$('download-input').disabled=true;$('brief-form').querySelectorAll('input,select,textarea').forEach(node=>node.disabled=true);try{let data;if(key==='blank')data={schema_version:1,mandate:Object.fromEntries(fields.map(([key])=>[key,null])),evidence:{}};else{const response=await fetch('data/'+key+'.json');if(!response.ok)throw new Error('Could not load the example. Choose it again to retry.');data=await response.json();}if(id!==loadId)return;fill(data);setBusy(false);$('brief-origin').textContent=key==='blank'?'YOUR INPUT':'FICTIONAL EXAMPLE';$('sample-note').textContent=notes[key];clearReport('Brief ready. Prepare the review to inspect the boundaries.');}catch(error){if(id!==loadId)return;$('status').textContent=error.message;setBadge('LOAD ERROR','error');}}
function tab(name,focus=false){document.querySelectorAll('[data-panel]').forEach(button=>{const active=button.dataset.panel===name;button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;$('panel-'+button.dataset.panel).hidden=!active;if(active&&focus)button.focus();});}
function render(files){const draft=JSON.parse(files['mandate-draft.json']);const pack=JSON.parse(files['scenario-tests.json']);if(draft.active!==false||draft.status!=='draft'||pack.live_actions!==false||pack.cases.some(c=>c.status!=='not_run'))throw new Error('The review did not preserve its inactive state.');latest=files;const decisions=draft.findings.filter(x=>x.severity==='decision'),coverage=draft.findings.filter(x=>x.severity==='integration');$('empty-state').hidden=true;$('report').hidden=false;setBadge(decisions.length?'HUMAN INPUT':'HUMAN REVIEW',decisions.length?'review':'ready');$('status').textContent=decisions.length?'Draft prepared. Resolve the decisions below with the responsible people.':'Draft prepared for human review. No authority has been granted.';$('agent-title').textContent=draft.mandate.agent_name||'Unnamed agent';$('review-summary').textContent=draft.mandate.purpose||'Purpose needs human input.';$('decision-count').textContent=decisions.length;$('coverage-count').textContent=coverage.length;$('scenario-count').textContent=pack.cases.length;const list=$('findings');list.replaceChildren();for(const item of draft.findings){const card=el('article',undefined,'finding '+item.severity);card.append(el('span',item.severity==='integration'?'RUNTIME VERIFICATION':'HUMAN DECISION','tag'),el('h4',findingTitles[item.code]||item.code),el('p',item.detail),el('p',item.fields.map(k=>labels[k]||k).join(' · '),'fields-note'));list.append(card);}if(!draft.findings.length)list.append(el('p','No document-consistency findings. Human review and runtime validation are still required.','help'));const matrix=$('matrix');matrix.replaceChildren();for(const [key,label] of fields){const row=el('tr');row.append(el('td',label),el('td',display(draft.mandate[key],key)),el('td',draft.evidence[key]||'Needs source note'));matrix.append(row);}const cases=$('scenarios');cases.replaceChildren();for(const item of pack.cases){const details=el('details',undefined,'scenario');details.append(el('summary',item.id+' · '+item.name),el('p','NOT RUN','tag'),el('p',item.expected_assertion),el('pre',JSON.stringify(item.setup,null,2)),el('p',item.missing_inputs.length?'Missing inputs: '+item.missing_inputs.map(k=>labels[k]||k).join(', '):'No missing inputs for this specification.'));cases.append(details);}tab('findings');$('runtime-note').textContent='Prepared locally with the original NIVQRA Python compiler.';}
function stop(message){runId++;worker?.terminate();worker=null;clearTimeout(timer);setBusy(false);clearReport(message);setBadge('STOPPED');preview();}
function prepare(event){event.preventDefault();if(busy)return;let input;try{input=JSON.stringify(collect());if(new TextEncoder().encode(input).length>250000)throw new Error('Use a brief smaller than 250 KB.');}catch(error){clearReport(error.message);setBadge('INPUT ERROR','error');if(error.field){const node=$('field-'+error.field);node.closest('details').open=true;node.setAttribute('aria-invalid','true');node.focus();}return;}clearReport('Loading the compiler and preparing your review…');setBadge('PREPARING');setBusy(true);const id=++runId;try{if(!worker)worker=new Worker('worker.js?v=1',{type:'module'});worker.onmessage=({data})=>{if(data.id!==runId)return;clearTimeout(timer);setBusy(false);if(data.ok){try{render(data.files);}catch(error){clearReport(error.message);setBadge('ERROR','error');}}else{if(data.errorType==='runtime')console.error('NIVQRA runtime:',data.diagnostic);clearReport(data.error);setBadge(data.errorType==='runtime'?'LOAD ERROR':'INPUT ERROR','error');}preview();};worker.onerror=()=>{stop('The compiler could not load. Check your connection and retry, or use the Python package linked under Source.');setBadge('LOAD ERROR','error');};timer=setTimeout(()=>stop('The review took too long. Retry with a shorter brief.'),90000);worker.postMessage({id,input});}catch(error){stop(error.message);setBadge('ERROR','error');}}
function download(name,content){const mime=name.endsWith('.json')?'application/json':name.endsWith('.csv')?'text/csv;charset=utf-8':'text/markdown;charset=utf-8';const url=URL.createObjectURL(new Blob([content],{type:mime}));const a=el('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
buildForm();$('example').addEventListener('change',()=>loadExample($('example').value));$('brief-form').addEventListener('submit',prepare);$('brief-form').addEventListener('input',event=>{event.target.removeAttribute('aria-invalid');$('brief-origin').textContent='EDITED BRIEF';$('sample-note').textContent='Your supplied edits are recorded in the input source notes. Blank fields remain unknown.';clearReport();preview();});$('cancel').addEventListener('click',()=>stop('Review cancelled. Your brief is preserved.'));$('download-input').addEventListener('click',()=>{if(busy)return;try{download('nivqra-input.json',JSON.stringify(collect(),null,2)+'\n');}catch(error){clearReport(error.message);setBadge('INPUT ERROR','error');}});document.querySelectorAll('[data-download]').forEach(button=>button.addEventListener('click',()=>{if(latest&&!busy)download(button.dataset.download,latest[button.dataset.download]);}));const tabs=[...document.querySelectorAll('[data-panel]')];tabs.forEach((button,index)=>{button.addEventListener('click',()=>tab(button.dataset.panel));button.addEventListener('keydown',event=>{let next;if(event.key==='ArrowRight')next=(index+1)%tabs.length;if(event.key==='ArrowLeft')next=(index+tabs.length-1)%tabs.length;if(event.key==='Home')next=0;if(event.key==='End')next=tabs.length-1;if(next!==undefined){event.preventDefault();tab(tabs[next].dataset.panel,true);}});});loadExample('procurement');
